// Generated by CoffeeScript 1.3.1
(function() {
  var DomTest;

  DomTest = (function() {

    DomTest.name = 'DomTest';

    function DomTest() {}

    DomTest.changeDescriptionExpectCorrectAltTag = function() {
      var element, expected;
      element = {};
      expected = 'Correct Description';
      Dom.changeDescription(element, expected);
      Assert.areIdentical(expected, element.alt);
      return Assert.areIdentical(expected, element.title);
    };

    return DomTest;

  })();

  Enhance.discoverTests(DomTest).runTests();

}).call(this);
