// Generated by CoffeeScript 1.3.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Dom = (function() {

    Dom.name = 'Dom';

    function Dom() {}

    Dom.changeDescription = function(element, description) {
      element.alt = description;
      return element.title = description;
    };

    return Dom;

  })();

}).call(this);
