// Generated by CoffeeScript 1.3.1
(function() {
  var ExamplesTest;

  ExamplesTest = (function() {

    ExamplesTest.name = 'ExamplesTest';

    function ExamplesTest() {}

    ExamplesTest.addTwoNumbersWith2and3Expect5 = function() {
      var result;
      result = Examples.addTwoNumbers(2, 3);
      Assert.areIdentical(5, result);
      return null;
    };

    return ExamplesTest;

  })();

  Enhance.discoverTests(ExamplesTest).runTests();

}).call(this);
