// Generated by CoffeeScript 1.3.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Examples = (function() {

    Examples.name = 'Examples';

    function Examples() {}

    Examples.addTwoNumbers = function(a, b) {};

    return Examples;

  })();

}).call(this);
