// Generated by CoffeeScript 1.3.1
(function() {
  var JqueryExampleTest, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.$;

  JqueryExampleTest = (function() {

    JqueryExampleTest.name = 'JqueryExampleTest';

    function JqueryExampleTest() {}

    JqueryExampleTest.changeDescriptionExpectCorrectAltTag = function() {
      var description, id, mock;
      id = 'test';
      description = 'Test Description';
      mock = MockRepository.generateMock([], ['attr']);
      mock.expect().method('attr').withArguments('alt', description).returns(mock).times(1);
      mock.expect().method('attr').withArguments('title', description).returns(mock).times(1);
      root.$ = function() {
        return mock;
      };
      JqueryExample.changeDescription(id, description);
      return mock.verifyExpectations();
    };

    return JqueryExampleTest;

  })();

  Enhance.discoverTests(JqueryExampleTest).runTests();

}).call(this);
