// Generated by CoffeeScript 1.3.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.JqueryExample = (function() {

    JqueryExample.name = 'JqueryExample';

    function JqueryExample() {}

    JqueryExample.changeDescription = function(id, description) {
      return $('#' + id).attr('alt', description).attr('title', description);
    };

    JqueryExample.doSomethingWithAjax = function(id, url) {
      return 'todo';
    };

    return JqueryExample;

  })();

}).call(this);
