// Generated by CoffeeScript 1.3.1
(function() {
  var JqueryExampleTest, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.$;

  JqueryExampleTest = (function() {

    JqueryExampleTest.name = 'JqueryExampleTest';

    function JqueryExampleTest() {}

    JqueryExampleTest.changeDescriptionExpectCorrectAltTag = function() {
      var classListMock, description, id, idTestMock;
      id = 'test';
      description = 'Test Description';
      idTestMock = MockRepository.generateJqueryMock('$', '#test').methods('attr');
      idTestMock.expect().method('attr').withArguments('alt', description).returns(idTestMock).times(1);
      idTestMock.expect().method('attr').withArguments('title', description).returns(idTestMock).times(1);
      classListMock = MockRepository.generateJqueryMock('$', '.list').methods('width');
      classListMock.expect().method('width').returns(321).times(1);
      JqueryExample.changeDescription(id, description);
      idTestMock.verifyExpectations();
      return classListMock.verifyExpectations();
    };

    return JqueryExampleTest;

  })();

  Enhance.discoverTests(JqueryExampleTest).runTests();

}).call(this);
