// Generated by CoffeeScript 1.3.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Sample = (function() {

    Sample.name = 'Sample';

    function Sample() {}

    Sample.addTwoNumbers = function() {
      return 5;
    };

    return Sample;

  })();

}).call(this);
