// Generated by CoffeeScript 1.3.1
(function() {
  var SampleTest;

  SampleTest = (function() {

    SampleTest.name = 'SampleTest';

    function SampleTest() {}

    SampleTest.addTwoNumbersWith2and3Expect5 = function() {
      var result;
      result = Sample.addTwoNumbers(2, 3);
      return Assert.areIdentical(5, result);
    };

    SampleTest.addTwoNumbersWith3and3Expect6 = function() {
      var result;
      result = Sample.addTwoNumbers(3, 3);
      return Assert.areIdentical(6, result);
    };

    return SampleTest;

  })();

  Enhance.discoverTests(SampleTest).runTests();

}).call(this);
